#!/bin/bash
# 🚀 Hermes Cloud Setup — runs once when the Codespace is created
# GitHub Codespaces secrets TELEGRAM_BOT_TOKEN and GH_TOKEN_FOR_API
# are automatically injected as environment variables.
set -e

echo "🔧 Installing Hermes Agent in cloud environment..."
cd ~

# Install hermes via pip
pip install --upgrade pip --quiet 2>/dev/null
pip install hermes-agent --quiet 2>/dev/null || {
    echo "⚠️ pip install failed, trying from source..."
    git clone --depth 1 https://github.com/nousresearch/hermes-agent.git /tmp/hermes-build 2>/dev/null || true
    if [ -f /tmp/hermes-build/pyproject.toml ]; then
        cd /tmp/hermes-build && pip install -e . --quiet && cd ~
    else
        echo "❌ Could not install hermes-agent. Manual install needed."
        exit 1
    fi
}

echo "✅ Hermes Agent installed ($(hermes --version 2>/dev/null || echo 'ok'))"

# Set up config directory
mkdir -p ~/.hermes/cron ~/.hermes/logs ~/.hermes/scripts

# Copy scripts from repo if available
if [ -d /workspaces/hermes-cloud/scripts ]; then
    cp /workspaces/hermes-cloud/scripts/*.py ~/.hermes/scripts/ 2>/dev/null || true
    chmod +x ~/.hermes/scripts/*.py 2>/dev/null || true
    echo "✅ Scripts installed"
fi

# Write .env with secrets from Codespaces environment
echo "# Hermes Cloud Gateway Config" > ~/.hermes/.env
echo "# Generated by setup-hermes.sh at $(date)" >> ~/.hermes/.env
echo "" >> ~/.hermes/.env

if [ -n "$TELEGRAM_BOT_TOKEN" ] && [ "$TELEGRAM_BOT_TOKEN" != "__SET_ME__" ]; then
    echo "TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN" >> ~/.hermes/.env
    echo "TELEGRAM_HOME_CHANNEL=5615834073" >> ~/.hermes/.env
    echo "TELEGRAM_ALLOWED_USERS=5615834073" >> ~/.hermes/.env
    echo "GATEWAY_ALLOW_ALL_USERS=true" >> ~/.hermes/.env
    echo "✅ Telegram token configured from Codespaces secret"
else
    echo "TELEGRAM_BOT_TOKEN=__SET_ME__" >> ~/.hermes/.env
    echo "TELEGRAM_HOME_CHANNEL=5615834073" >> ~/.hermes/.env
    echo "TELEGRAM_ALLOWED_USERS=5615834073" >> ~/.hermes/.env
    echo "GATEWAY_ALLOW_ALL_USERS=true" >> ~/.hermes/.env
    echo "⚠️  TELEGRAM_BOT_TOKEN not in env. Set it manually in ~/.hermes/.env"
fi

if [ -n "$GH_TOKEN_FOR_API" ]; then
    echo "export GITHUB_TOKEN=$GH_TOKEN_FOR_API" >> ~/.hermes/.env
    echo "✅ GitHub API token configured from Codespaces secret"
fi

# Write config.yaml
mkdir -p ~/.hermes
cat > ~/.hermes/config.yaml << 'CEOF'
gateway:
  enabled: true
  providers:
    - telegram
  port: 3000
  allow_all_users: true

cron:
  enabled: true
  scripts_dir: ~/.hermes/scripts/

model:
  provider: opencode-zen
  model: big-pickle
CEOF
echo "✅ Config written"

# Set up cron for health check + memory pull
(crontab -l 2>/dev/null; echo "*/30 * * * * cd /workspaces/hermes-cloud && python3 scripts/cloud_memory_pull.py 2>/dev/null || true") | crontab -
echo "✅ Cron: health check + memory pull installed"

# Set git config (so hermes doesn't complain)
git config --global user.email "sofiane@hermes-cloud" 2>/dev/null || true
git config --global user.name "Sofiane (Cloud)" 2>/dev/null || true

# Write setup marker
echo "✅ Hermes Cloud setup complete at $(date)" > ~/.hermes/cloud-setup-done

# Pull latest memory from local
if [ -f /workspaces/hermes-cloud/scripts/cloud_memory_pull.py ]; then
    echo ""
    echo "📥 Pulling latest memory from local..."
    python3 /workspaces/hermes-cloud/scripts/cloud_memory_pull.py
fi

echo ""
echo "╔════════════════════════════════════╗"
echo "║  🚀  HERMES CLOUD READY          ║"
echo "╠════════════════════════════════════╣"
echo "║  Run: bash .devcontainer/start-   ║"
echo "║       gateway.sh                  ║"
echo "║  To start the gateway             ║"
echo "╚════════════════════════════════════╝"
