#!/bin/bash
# 🚀 Hermes Cloud Setup — runs once when the Codespace is created
# Transforms the cloud from a dumb gateway into a full Hermes agent
# with cron scheduling, agent capabilities, and inter-agent communication.

set -e

echo "🔧 Installing Hermes Agent in cloud environment..."
cd ~

# Install hermes via pip
pip install --upgrade pip --quiet 2>/dev/null
pip install hermes-agent --quiet 2>/dev/null || {
    echo "⚠️ pip install failed, trying from source..."
    git clone --depth 1 https://github.com/nousresearch/hermes-agent.git /tmp/hermes-build 2>/dev/null || true
    if [ -f /tmp/hermes-build/pyproject.toml ]; then
        cd /tmp/hermes-build && pip install -e . --quiet && cd ~
    else
        echo "❌ Could not install hermes-agent. Manual install needed."
        exit 1
    fi
}

echo "✅ Hermes Agent installed ($(hermes --version 2>/dev/null || echo 'ok'))"

# Set up config directory
mkdir -p ~/.hermes/{cron,logs,scripts,memories,skills}

# Copy scripts from repo if available
if [ -d /workspaces/hermes-cloud/scripts ]; then
    cp /workspaces/hermes-cloud/scripts/*.py ~/.hermes/scripts/ 2>/dev/null || true
    chmod +x ~/.hermes/scripts/*.py 2>/dev/null || true
    echo "✅ Scripts installed"
fi

# Write cloud .env with secrets from Codespaces environment
echo "# Hermes Cloud Gateway — Full Agent Config" > ~/.hermes/.env
echo "# Generated by setup-hermes.sh at $(date)" >> ~/.hermes/.env
echo "" >> ~/.hermes/.env

if [ -n "$TELEGRAM_BOT_TOKEN" ] && [ "$TELEGRAM_BOT_TOKEN" != "__SET_ME__" ]; then
    echo "TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN" >> ~/.hermes/.env
    echo "TELEGRAM_HOME_CHANNEL=5615834073" >> ~/.hermes/.env
    echo "TELEGRAM_ALLOWED_USERS=5615834073" >> ~/.hermes/.env
    echo "✅ Telegram token configured"
else
    echo "TELEGRAM_BOT_TOKEN=__SET_ME__" >> ~/.hermes/.env
    echo "TELEGRAM_HOME_CHANNEL=5615834073" >> ~/.hermes/.env
    echo "TELEGRAM_ALLOWED_USERS=5615834073" >> ~/.hermes/.env
    echo "⚠️  TELEGRAM_BOT_TOKEN not in env. Set it in GitHub repo → Settings → Secrets → Codespaces"
fi

if [ -n "$GH_TOKEN_FOR_API" ]; then
    echo "GITHUB_TOKEN=$GH_TOKEN_FOR_API" >> ~/.hermes/.env
    echo "✅ GitHub API token configured"
fi

# Add webhook secret for cloud's own webhook platform
echo "MESH_WEBHOOK_SECRET=mesh-cloud-secret-change-me" >> ~/.hermes/.env

# Write FULL config.yaml — this is a real Hermes agent, not just a gateway relay
cat > ~/.hermes/config.yaml << 'CONFIGEOF'
model:
  provider: opencode-zen
  default: big-pickle
  base_url: https://opencode.ai/zen/v1

fallback_providers:
  - provider: opencode-zen
    model: deepseek-v4-flash-free
  - provider: opencode-zen
    model: nemotron-3-ultra-free

gateway:
  enabled: true
  providers:
    - telegram
  port: 3000

cron:
  enabled: true
  output_retention: 50
  wrap_response: true

platforms:
  webhook:
    enabled: true
    extra:
      host: "0.0.0.0"
      port: 8644
      secret: "mesh-cloud-secret-change-me"

skills:
  external_dirs: []
  template_vars: true

memory:
  memory_enabled: true
  user_profile_enabled: true
  memory_char_limit: 2200
  user_char_limit: 1375

toolsets:
  - hermes-cli

agent:
  max_turns: 60
  tool_use_enforcement: auto
  task_completion_guidance: true
  parallel_tool_call_guidance: true

delegation:
  max_concurrent_children: 3
  max_spawn_depth: 1
  orchestrator_enabled: true
  child_timeout_seconds: 600

display:
  compact: true
  interface: cli
  timestamps: false
  show_cost: true

security:
  redact_secrets: true
  tirith_enabled: false

terminal:
  backend: local
  timeout: 180
CONFIGEOF
echo "✅ Full agent config written (~/.hermes/config.yaml)"

# Set up webhook subscriptions for agent-to-agent communication
echo "🔗 Setting up agent mesh webhooks..."
hermes webhook subscribe local-task \
  --prompt 'A task arrived from the local Hermes agent. Process it with your tool access.\n\nTask: {payload}\n\nExecute and deliver results via Telegram.' \
  --events 'task.execute' \
  --deliver telegram \
  --secret 'mesh-cloud-secret-change-me' 2>/dev/null || echo "⚠️ Webhook setup deferred (gateway not running yet)"

hermes webhook subscribe knowledge-share \
  --prompt 'Knowledge shared from the local agent. Store in memory if valuable.\n\nKnowledge: {payload}\n\nConfirm receipt.' \
  --events 'knowledge.share' \
  --deliver telegram \
  --secret 'mesh-cloud-secret-change-me' 2>/dev/null || echo "⚠️ Knowledge webhook deferred"

# Set git config
git config --global user.email "sofiane@hermes-cloud" 2>/dev/null || true
git config --global user.name "Sofiane (Cloud)" 2>/dev/null || true

# Write setup marker
echo "✅ Hermes Cloud setup complete at $(date)" > ~/.hermes/cloud-setup-done

# Pull latest memory from local
if [ -f /workspaces/hermes-cloud/scripts/cloud_memory_pull.py ]; then
    echo ""
    echo "📥 Pulling latest memory from local..."
    python3 /workspaces/hermes-cloud/scripts/cloud_memory_pull.py
fi

echo ""
echo "╔═══════════════════════════════════════════════╗"
echo "║  ☁️  HERMES CLOUD — FULL AGENT READY         ║"
echo "╠═══════════════════════════════════════════════╣"
echo "║  Telegram: bot responds 24/7                  ║"
echo "║  Cron: all jobs scheduled                     ║"
echo "║  Webhook: port 8644 for agent mesh            ║"
echo "║  Memory: synced from local                    ║"
echo "║                                               ║"
echo "║  Start: bash .devcontainer/start-gateway.sh   ║"
echo "╚═══════════════════════════════════════════════╝"
